# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.download.defaultFolder", "/home/demmer");
user_pref("browser.download.openSidebar", true);
user_pref("browser.download.useProgressDialogs", false);
user_pref("browser.preferences.lastpanel", 5);
user_pref("browser.startup.homepage", "http://my.yahoo.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.6");
user_pref("browser.xul.error_pages.enabled", true);
user_pref("font.name.monospace.x-western", "Courier");
user_pref("font.name.sans-serif.x-western", "LucidaTypewriter");
user_pref("font.name.serif.x-western", "serif");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1");
user_pref("javascript.enabled", false);
user_pref("keyword.URL", "http://www.google.com/search?btnG=Google+Search&q=");
user_pref("network.image.imageBehavior", 0);
user_pref("prefs.converted-to-utf8", true);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
