# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.download.dir", "/home/demmer/downloads");
user_pref("browser.download.lastDir", "/tmp");
user_pref("browser.download.openSidebar", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.download.useProgressDialogs", false);
user_pref("browser.startup.homepage", "http://my.yahoo.com/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.7");
user_pref("browser.tabs.autoHide", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.xul.error_pages.enabled", true);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("keyword.URL", "http://www.google.com/search?btnG=Google+Search&q=");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.popups.firstTime", false);
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_viewing_mixed", false);
